const Progress = [
  {
    field: "format",
    desc: "内容的模板函数",
    type: "function(percent, successPercent)",
    default: "(percent) => percent + %",
  },
  {
    field: "percent",
    desc: "百分比",
    type: "number",
    default: "0",
  },
  {
    field: "showInfo",
    desc: "是否显示进度数值或状态图标",
    type: "boolean",
    default: "true",
  },
  {
    field: "status",
    desc: "状态",
    type: "`success` \\| `exception` \\| `normal` \\| `active`",
    default: "false",
  },
  {
    field: "strokeColor",
    desc: "进度条的色彩",
    type: "string",
    default: "-",
  },
  {
    field: "strokeLinecap",
    desc: "进度条的样式",
    type: "`round` \\| `square`",
    default: "round",
  },
  {
    field: "success",
    desc: "成功进度条相关配置",
    type: "{ percent: number, strokeColor: string }",
    default: "-",
  },
  {
    field: "trailColor",
    desc: "未完成的分段的颜色",
    type: "string",
    default: "-",
  },
  {
    field: "type",
    desc: "类型",
    type: "`line` \\| `circle` \\| `dashboard`",
    default: "true",
  },
  {
    field: 'type="line"',
    desc: '以下属性在type="line"时生效',
    type: "-",
    default: "-",
  },
  {
    field: "steps",
    desc: "进度条总共步数",
    type: "number",
    default: "-",
  },
  {
    field: "strokeColor",
    desc: "进度条的色彩，传入 object 时为渐变",
    type: "string \\| { from: string; to: string; direction: string }",
    default: "-",
  },
  {
    field: "strokeWidth",
    desc: "进度条线的宽度，单位 px",
    type: "number",
    default: "10",
  },
  {
    field: 'type="circle"',
    desc: '以下属性在type="circle"时生效',
    type: "-",
    default: "-",
  },
  {
    field: "strokeColor",
    desc: "圆形进度条线的色彩，传入 object 时为渐变",
    type: "string \\| object",
    default: "-",
  },
  {
    field: "strokeWidth",
    desc: "圆形进度条线的宽度，单位是进度条画布宽度的百分比",
    type: "number",
    default: "6",
  },
  {
    field: "width",
    desc: "圆形进度条画布宽度，单位 px",
    type: "number",
    default: "132",
  },
  {
    field: 'type="dashboard"',
    desc: '以下属性在type="dashboard"时生效',
    type: "-",
    default: "-",
  },
  {
    field: "gapDegree",
    desc: "仪表盘进度条缺口角度，可取值 0 ~ 295",
    type: "number",
    default: "75",
  },
  {
    field: "gapPosition",
    desc: "仪表盘进度条缺口位置",
    type: "`top` \\| `bottom` \\| `left` \\| `right`",
    default: "bottom",
  },
  {
    field: "strokeWidth",
    desc: "仪表盘进度条线的宽度，单位是进度条画布宽度的百分比",
    type: "number",
    default: "6",
  },
  {
    field: "width",
    desc: "仪表盘进度条画布宽度，单位 px",
    type: "number",
    default: "132",
  },
];

module.exports = Progress;
