const Select = [
  {
    field: "allowClear",
    desc: "支持清除",
    type: "boolean",
    default: "false",
  },
  {
    field: "autoClearSearchValue",
    desc: "是否在选中项后清空搜索框，只在 mode 为 multiple 或 tags 时有效",
    type: "boolean",
    default: "true",
  },
  {
    field: "autoFocus",
    desc: "默认获取焦点",
    type: "boolean",
    default: "false",
  },
  {
    field: "bordered",
    desc: "是否有边框",
    type: "boolean",
    default: "true",
  },
  {
    field: "clearIcon",
    desc: "自定义的多选框清空图标",
    type: "ReactNode",
    default: "-",
  },
  {
    field: "defaultActiveFirstOption",
    desc: "是否默认高亮第一个选项",
    type: "boolean",
    default: "true",
  },
  {
    field: "defaultOpen",
    desc: "是否默认展开下拉菜单",
    type: "boolean",
    default: "-",
  },
  {
    field: "defaultValue",
    desc: "指定默认选中的条目",
    type: "string \\| string[] \\| number \\| number[] \\| LabeledValue \\| LabeledValue[]",
    default: "-",
  },
  {
    field: "disabled",
    desc: "是否禁用",
    type: "boolean",
    default: "false",
  },
  {
    field: "dropdownClassName",
    desc: "下拉菜单的 className 属性",
    type: "string",
    default: "-",
  },
  {
    field: "dropdownMatchSelectWidth",
    desc: "下拉菜单和选择器同宽。默认将设置 min-width，当值小于选择框宽度时会被忽略。false 时会关闭虚拟滚动",
    type: "boolean \\| number",
    default: "true",
  },
  {
    field: "dropdownRender",
    desc: "自定义下拉框内容",
    type: "(originNode: ReactNode) => ReactNode",
    default: "-",
  },
  {
    field: "dropdownStyle",
    desc: "下拉菜单的 style 属性",
    type: "CSSProperties",
    default: "-",
  },
  {
    field: "fieldNames",
    desc: "自定义节点 label、key、options 的字段",
    type: "object",
    default: "{ label: label, key: key, options: options }",
  },
  {
    field: "filterOption",
    desc: "是否根据输入项进行筛选。当其为一个函数时，会接收 inputValue option 两个参数，当 option 符合筛选条件时，应返回 true，反之则返回 false",
    type: "boolean \\| function(inputValue, option)",
    default: "true",
  },
  {
    field: "filterSort",
    desc: "搜索时对筛选结果项的排序函数, 类似Array.sort里的 compareFunction",
    type: "(optionA: Option, optionB: Option) => number",
    default: "-",
  },
  {
    field: "getPopupContainer",
    desc: "菜单渲染父节点。默认渲染到 body 上，如果你遇到菜单滚动定位问题，试试修改为滚动的区域，并相对其定位。",
    type: "function(triggerNode)",
    default: "() => document.body",
  },
  {
    field: "labelInValue",
    desc: "是否把每个选项的 label 包装到 value 中，会把 Select 的 value 类型从 string 变为 { value: string, label: ReactNode } 的格式",
    type: "boolean",
    default: "false",
  },
  {
    field: "listHeight",
    desc: "设置弹窗滚动高度",
    type: "number",
    default: "256",
  },
  {
    field: "loading",
    desc: "加载中状态",
    type: "boolean",
    default: "false",
  },
  {
    field: "maxTagCount",
    desc: "最多显示多少个 tag，响应式模式会对性能产生损耗",
    type: "number \\| responsive",
    default: "-",
  },
  {
    field: "maxTagPlaceholder",
    desc: "隐藏 tag 时显示的内容",
    type: "ReactNode | function(omittedValues)",
    default: "-",
  },
  {
    field: "maxTagTextLength",
    desc: "最大显示的 tag 文本长度",
    type: "number",
    default: "-",
  },
  {
    field: "menuItemSelectedIcon",
    desc: "自定义多选时当前选中的条目图标",
    type: "ReactNode",
    default: "-",
  },
  {
    field: "mode",
    desc: "设置 Select 的模式为多选或标签",
    type: "multiple \\| tags",
    default: "-",
  },
  {
    field: "notFoundContent",
    desc: "当下拉列表为空时显示的内容",
    type: "ReactNode",
    default: "Not Found",
  },
  {
    field: "open",
    desc: "是否展开下拉菜单",
    type: "boolean",
    default: "-",
  },
  {
    field: "optionFilterProp",
    desc: '搜索时过滤对应的 option 属性，如设置为 children 表示对内嵌内容进行搜索。若通过 options 属性配置选项内容，建议设置 optionFilterProp="label" 来对内容进行搜索。',
    type: "string",
    default: "value",
  },
  {
    field: "optionLabelProp",
    desc: "回填到选择框的 Option 的属性值，默认是 Option 的子元素。比如在子元素需要高亮效果时，此值可以设为 value。",
    type: "string",
    default: "children",
  },
  {
    field: "options",
    desc: "数据化配置选项内容，相比 jsx 定义会获得更好的渲染性能",
    type: "{ label, value }[]",
    default: "-",
  },
  {
    field: "placeholder",
    desc: "选择框默认文本",
    type: "string",
    default: "-",
  },
  {
    field: "removeIcon",
    desc: "自定义的多选框清除图标",
    type: "ReactNode",
    default: "-",
  },
  {
    field: "searchValue",
    desc: "控制搜索文本",
    type: "string",
    default: "-",
  },
  {
    field: "showArrow",
    desc: "是否显示下拉小箭头",
    type: "boolean",
    default: "单选为 true，多选为 false",
  },
  {
    field: "showSearch",
    desc: "使单选模式可搜索",
    type: "boolean",
    default: "false",
  },
  {
    field: "size",
    desc: "选择框大小",
    type: "`large` \\| `middle` \\| `small`",
    default: "middle",
  },
  {
    field: "suffixIcon",
    desc: "自定义的选择框后缀图标",
    type: "ReactNode",
    default: "-",
  },
  {
    field: "tagRender",
    desc: "自定义 tag 内容 render",
    type: "(props) => ReactNode",
    default: "-",
  },
  {
    field: "tokenSeparators",
    desc: "在 tags 和 multiple 模式下自动分词的分隔符",
    type: "string[]",
    default: "-",
  },
  {
    field: "value",
    desc: "指定当前选中的条目，多选时为一个数组。（value 数组引用未变化时，Select 不会更新）",
    type: "string \\| string[] \\| number \\| number[] \\| LabeledValue \\| LabeledValue[]",
    default: "-",
  },
  {
    field: "virtual",
    desc: "设置 false 时关闭虚拟滚动",
    type: "boolean",
    default: "true",
  },
  {
    field: "onBlur",
    desc: "失去焦点时回调",
    type: "function",
    default: "-",
  },
  {
    field: "onChange",
    desc: "选中 option，或 input 的 value 变化时，调用此函数",
    type: "function(value, option:Option \\| Array<Option>)",
    default: "-",
  },
  {
    field: "onClear",
    desc: "清除内容时回调",
    type: "function",
    default: "-",
  },
  {
    field: "onDeselect",
    desc: "取消选中时调用，参数为选中项的 value (或 key) 值，仅在 multiple 或 tags 模式下生效",
    type: "function(string \\| number \\| LabeledValue)",
    default: "-",
  },
  {
    field: "onDropdownVisibleChange",
    desc: "展开下拉菜单的回调",
    type: "function(open)",
    default: "-",
  },
  {
    field: "onFocus",
    desc: "获得焦点时回调",
    type: "function",
    default: "-",
  },
  {
    field: "onInputKeyDown",
    desc: "按键按下时回调",
    type: "function",
    default: "-",
  },
  {
    field: "onMouseEnter",
    desc: "鼠标移入时回调",
    type: "function",
    default: "-",
  },
  {
    field: "onMouseLeave",
    desc: "鼠标移出时回调",
    type: "function",
    default: "-",
  },
  {
    field: "onPopupScroll",
    desc: "下拉列表滚动时的回调",
    type: "function",
    default: "-",
  },
  {
    field: "onSearch",
    desc: "文本框值变化时回调",
    type: "function(value: string)",
    default: "-",
  },
  {
    field: "onSelect",
    desc: "被选中时调用，参数为选中项的 value (或 key) 值",
    type: "function(string \\| number \\| LabeledValue, option: Option)",
    default: "-",
  },
];

module.exports = Select;
